### PR TITLE
[ja-translation] Use iframe for video embedding

### PR DESCRIPTION
**Pull request by maybe-eve**
I found that Firefox blocks video embedding using ```<script>```, so I replaced it with ```<iframe>```.

Tested on local and worked correctly.

### CODE REVIEW

**Comment by maybe-eve** [comment]
Uhm, it seems Firefox blocks any embedded video from nicovideo.jp ...

**Comment by ayust** [comment]
Hm. When you tested, does it actually play? If I try to load the iframe, the iframe shows up, but then if I try to press Play, it instead says that it can't be watched in that player and must be watched on Niconico.

**Comment by ayust** [comment]
If we can't get an embed to work properly, you could also just link to the video on Niconico instead.

**Comment by maybe-eve** [comment]
sm25333115 didn't allow embedding, so I replaced it with sm24971863. (https://github.com/ayust/alpha-guide/pull/14/commits/1b4a7e69b0317a82ebd3b63259b2b532462820c5)

Here is the screenshot of local testing:


but it seems it is blocked in [the deploy preview](https://deploy-preview-15--alpha-guide-ja.netlify.com/new-goals/something-else/) .

**Comment by ayust** [comment]
Right. The reason it doesn't work in the deploy is because the niconico url is HTTP, and the deployed version is HTTPS, resulting in the following error in Chrome:

> Mixed Content: The page at 'https://deploy-preview-15--alpha-guide-ja.netlify.com/new-goals/something-else/' was loaded over HTTPS, but requested an insecure resource 'http://embed.nicovideo.jp/watch/sm24971863?oldScript=1'. This request has been blocked; the content must be served over HTTPS.

I don't know if Niconico supports HTTPS urls.

**Comment by maybe-eve** [comment]
Niconico still only supports HTTP... X)

It seems it is better to just link to that video.

**Comment by ayust** [comment]
Yes, that seems like the right option. Can you update the pull request to switch to a link?

**Comment by maybe-eve** [comment]
done :smile:

**Pull request merged**
